'use client';

// import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { RecoilRoot } from "recoil";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecoilRoot>
      <html lang="en">
        <head>
          <title>Consid commerce</title>
          <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
          <link href="https://fonts.googleapis.com/css2?family=Inter" rel="stylesheet" />
        </head>
        <body className="font-Inter">
          <Header />
          {children}
        </body>
      </html>
    </RecoilRoot>
  );
}
